packages/frontend/package.json
yarn.lock

Adds some auto-generated chromatic scripts while I get CI/CD for it sorted out (Their website ain't working too well).

Frontend(CI/CD): Add chromatic scripts

---

packages/backend/src/App.js
packages/backend/src/controllers/UserController.js
packages/backend/src/helpers/utils.js
packages/backend/src/lib/passport-local.js

Fixes the error handler of the API for the auth endpoints, which needed a different technique due to the endpoint depending on passportjs's internal auth result.

Backend(Controllers, errors): Normalize error structure

---

packages/backend/src/App.js
packages/backend/src/controllers/NetworkController.js
packages/backend/src/controllers/UserController.js
packages/backend/src/helpers/utils.js
packages/backend/src/lib/passport-local.js
packages/backend/src/middlewares/passport-auth.js
packages/frontend/package.json
packages/frontend/src/environment.js
packages/frontend/src/ui/style/constants.js
packages/frontend/src/views/Onboarding/Login.js
packages/frontend/src/views/Onboarding/Signup.js
yarn.lock

Integrates frontend and backend together for login/signup pages. There's still design / UX work to do, but it will be okay for testing as we iron out those details.

Backend, Frontend: add login/signup integration

---

packages/backend/src/controllers/ApplicationController.js
packages/frontend/src/views/Dashboard/Create/Create.js
packages/frontend/src/views/Dashboard/application-hooks.js
packages/frontend/src/views/DashboardRoutes.js

Properly wires up the create integration, taking into account the current state of the backend's app pool. Also blocks the view if the user already has an app.

Frontend, Backend: Create integration

---

packages/backend/src/controllers/ApplicationController.js
packages/backend/src/environment.js
packages/backend/src/models/Application.js
packages/frontend/src/views/Dashboard/ApplicationDetail/ApplicationDetail.js
packages/frontend/src/views/Dashboard/ApplicationDetail/Chains.js
packages/frontend/src/views/Dashboard/ApplicationDetail/Notifications.js

Hooks up both screens with the backend.

Backend, Frontend: Switch chains / notifications integrations

---

packages/backend/src/lib/pocket.js
packages/backend/src/workers/application.js
packages/backend/src/workers/config.js

As we get ready to deploy and start testing the workers, these are some slight changes to make sure we don't have much wastage if anything goes wrong.

Backend: misc. conditioning

---

packages/backend/package.json

Some little mistakes in how we start up production.

Backend: Fix prod setup

---

packages/backend/src/workers/application.js
packages/backend/src/workers/config.js

Temporarily staking less POKT but adding more apps for testing.

Backend(Workers): tune up workers for testing

---

packages/frontend/src/App.js
packages/frontend/src/ui/AppWrapper/AppWrapper.js
packages/frontend/src/ui/ToastHub/README.md
packages/frontend/src/ui/ToastHub/ToastHub.js
packages/frontend/src/ui/index.js
packages/frontend/src/views/Dashboard/ApplicationDetail/AppInfo.js
packages/frontend/src/views/Onboarding/Signup.js

Adds toast notifications to the dashboard. 🥂

Frontend(UI): Add toast notifications

---

packages/frontend/src/views/Onboarding/ForgotPassword.js
packages/frontend/src/views/Onboarding/Login.js
packages/frontend/src/views/Onboarding/NewPassword.js
packages/frontend/src/views/Onboarding/Signup.js

Also adds correct links for T&C and Privacy Policy.

Frontend(Login, Signup, New Password): Move errors to corresponding inputs

---

packages/frontend/src/views/Dashboard/ApplicationDetail/Notifications.js
packages/frontend/src/views/Dashboard/NavigationBar.js

- Adds a dynamic title for pages depending on the route
- Copy fixes
- Community link

Frontend: QA UI Enhancements

---

packages/backend/src/environment.js
packages/backend/src/workers/application.js
packages/backend/src/workers/config.js

** CHECK AFTER MERGING **
Once all of this is done, this PR can be merged.

Backend(Workers): Set workers on production mode

---

packages/frontend/src/components/AppStatus/AppStatus.js
packages/frontend/src/ui/Button/Button.js
packages/frontend/src/views/Dashboard/ApplicationDetail/Notifications.js
packages/frontend/src/views/Dashboard/ApplicationDetail/SuccessDetails.js
packages/frontend/src/views/Dashboard/Network/NetworkInfo.js

Changes copy / sizes on various places of the app.

Copy: misc. fixes throughout the app

---

packages/backend/src/controllers/UserController.js
packages/backend/src/lib/passport-local.js
packages/frontend/src/views/DashboardRoutes.js
packages/frontend/src/views/Onboarding/NewPassword.js
packages/frontend/src/views/Onboarding/Signup.js
packages/frontend/src/views/Onboarding/Validate.js

Encodes/decodes URI params to allow for special chars to appear on emails/tokens. This is the silly error that was preventing signups from "+ emails". Closes #104.

Auth: properly encode/decode URI components

---

packages/frontend/src/views/Onboarding/NewPassword.js
packages/frontend/src/views/Onboarding/Signup.js

The previous password validation message was lacking a few indications.

Auth: fix password validation message copy

---

packages/frontend/src/components/AppStatus/AppStatus.js
packages/frontend/src/components/Box/Box.js
packages/frontend/src/ui/Button/Button.js
packages/frontend/src/ui/Tag/Tag.js
packages/frontend/src/ui/TextCopy/TextCopy.js
packages/frontend/src/ui/style/text-styles.js
packages/frontend/src/views/Dashboard/ApplicationDetail/AppInfo.js
packages/frontend/src/views/Dashboard/ApplicationDetail/Notifications.js
packages/frontend/src/views/Dashboard/ApplicationDetail/SuccessDetails.js
packages/frontend/src/views/Dashboard/NavigationBar.js
packages/frontend/src/views/Dashboard/Network/NetworkStatus.js

Introduces the new font hierarchy as per the style guide on most pages. `textStyle()` might get an overhaul soon, but it'll be later as it requires some more discussions with design.

Frontend: Fix font hierarchy + various misalignments

---

packages/frontend/src/views/Dashboard/ApplicationDetail/AppInfo.js
packages/frontend/src/views/Dashboard/ApplicationDetail/SuccessDetails.js

Marks blank methods in the request details page as unknown, instead of leaving them blank, for the sake of consistency.

Request Details: mark blank methods as unknown, light refactor

---

packages/backend/src/controllers/UserController.ts
packages/backend/src/lib/passport-local.ts

Login: handle internal errors correctly

---

packages/backend/src/controllers/ApplicationController.ts
packages/backend/src/workers/config.ts
packages/frontend/src/views/Dashboard/Create/Create.js

Mainly due to incoming traffic coming from a future Dark Forest integration. Gotta have them apps!

Workers, Applications: enable xdai apps, remove 1 app-per-account limit

---

packages/backend/src/lib/passport-local.ts

Avoids random errors on signup/login.

Auth: fix Passport verification

---

packages/backend/src/controllers/UserController.ts

Auth: properly throw on login/signup errors

---

packages/backend/src/controllers/UserController.ts

Reverts pokt-foundation/portal-frontend#150

Revert "Auth: properly throw on login/signup errors"

---

packages/backend/src/workers/config.ts

We support all ETH testnets, we're enabling the workers for these.

chore(workers): add Goerli, Kovan

---

packages/backend/src/workers/config.ts

This will be changed to be pulled on-chain, but now apps can stake much less POKT and get a million relays, which also concerns us as we can now use less POKT for more apps. 🙌

Backend(Workers): Change stake amount.

---

packages/backend/src/models/Application.ts
packages/backend/src/workers/application.ts

Encrypts sensitive app fields.

Backend: properly encrypt sensitive fields

---

packages/backend/src/controllers/LoadBalancerController.ts
packages/frontend/src/components/MenuPanel/MenuPanel.js

Temporarily removing the restrictions for apps per account until we decide to lock it down again.

Apps: allow multiple apps per account

---

packages/frontend/package.json
packages/frontend/src/components/Box/Box.js
packages/frontend/src/components/Onboarding/Onboarding.js
packages/frontend/src/views/Dashboard/ApplicationDetail/AppInfo.js
packages/frontend/src/views/Dashboard/Network/NetworkStatus.js
packages/frontend/src/views/Onboarding/ForgotPassword.js
packages/frontend/src/views/Onboarding/Login.js
packages/frontend/src/views/Onboarding/NewPassword.js
packages/frontend/src/views/Onboarding/Signup.js
packages/frontend/src/views/Onboarding/Validate.js
yarn.lock

Frontend: several spacing changes

---

packages/backend/src/services/MailgunService.ts
packages/backend/src/workers/index.ts

Emails: change email sender

---

packages/frontend/package.json
packages/frontend/public/manifest.json
packages/frontend/src/components/MenuPanel/MenuPanel.js
packages/frontend/src/components/OnboardingHeader/OnboardingHeader.js
packages/frontend/src/contexts/AppsContext.js
packages/frontend/src/sentry.js
packages/frontend/src/views/Dashboard/ApplicationDetail/AppInfo.js
packages/frontend/src/views/Dashboard/ApplicationDetail/Notifications.js
packages/frontend/src/views/Dashboard/ApplicationDetail/Security.js
packages/frontend/src/views/Dashboard/ApplicationDetail/SuccessDetails.js
packages/frontend/src/views/Dashboard/Create/Create.js
packages/frontend/src/views/Dashboard/NavigationBar.js
packages/frontend/src/views/Dashboard/Network/NetworkStatus.js
packages/frontend/src/views/Fallback.js
packages/frontend/src/views/Onboarding/Signup.js

Updates copy all over the place to the (almost) final copy for the release.

General: copy changes + max apps modal

---

packages/frontend/public/index.html

100% private and self hosted—but there's still things we want to track!

Analytics: add private analytics countly script

---

.github/workflows/staging.yml
packages/backend/src/helpers/utils.ts
packages/backend/src/models/Application.ts
packages/backend/src/models/LoadBalancer.ts

Includes hotfix to fix LB api endpoint failing for users created with social sign ons
updates environment branch from staging to stage.
will decommission "staging" branch after this.

Push stage to production
